### ISSUE TITLE
 Authentication require or incorrect

### ISSUE THREAD

**Issue by keunes** [hippojay/plugin.video.plexbmc#178]
I have the same issue as #21, but it only started after creating an account with Plex and connecting it to the server. I can login to PMS's web interface using the login details via localhost, but using the same details in PleXBMC doesn't work.
- PleXBMC version 3.4.4
- Plex 1.1.4.2757
- Kodi 15.2 (28 Dec 2015)
- Raspbian Jessie

PleXBMC does find my PMS, connecting via auto (GDM) or manually doesn't make a difference. Could it possibly matter which user Plex and/or Kodi(+PleXBMC) are running?

**Comment by keunes** [comment]
The log: [PleXBMC.txt](https://github.com/hippojay/plugin.video.plexbmc/files/531854/PleXBMC.txt)

**Comment by pburgh19** [comment]
I have the same issue, though my setup is slightly different:

- PleXMBC version 3.4.5
- Plex 1.2.7.2987  hosted on Windows 7 64bit
- Kodi 16.0 (Git:20160220-a5f3a99)

I have three instances of Kodi (one Windows 7 and two Raspberry Pi) and they are display the same error "authentication require or incorrect."  

This all worked flawlessly for the last year until _something_ busted.

**Comment by draggy** [comment]
This is because of the new plex authentication: https://support.plex.tv/hc/en-us/articles/200430283-Network

In the Plex web settings: Network -> Show Advanced -> "List of IP addresses and networks that are allowed without auth"

Either put in a comma delimited list of the ips that need access to the plex server or put in an ip range. If your network is 192.168.0.xxx then you would put "192.168.0.0/255.255.255.0" to allow access to PMS for all local PCs

**Comment by pburgh19** [comment]
That did the trick.  Thank you!
