### ISSUE TITLE
Authentication error on latest source

### ISSUE THREAD

**Issue by sintaxasn** [hippojay/plugin.video.plexbmc#46]
Hey there,

Just pulled the latest code and I'm seeing the following error, (server IP masked):

21:07:18 T:41624  NOTICE: PleXBMC -> Mode: 0
21:07:18 T:41624  NOTICE: PleXBMC -> URL: http://xx.xxx.xx.xxx:13892/library/sections/2
21:07:18 T:41624  NOTICE: PleXBMC -> Name:
21:07:18 T:41624  NOTICE: PleXBMC -> identifier: None
21:07:18 T:41624  NOTICE: PleXBMC -> token: None
21:07:18 T:41624  NOTICE: PleXBMC -> getContent : == ENTER ==
21:07:18 T:41624  NOTICE: PleXBMC -> getContent : URL suffix: 2
21:07:18 T:41624  NOTICE: PleXBMC -> getURL : == ENTER ==
21:07:18 T:41624  NOTICE: PleXBMC -> getURL : url = http://xx.xxx.xx.xxx:13892/library/sections/2
21:07:18 T:41624  NOTICE: PleXBMC -> getURL : header = {}
21:07:18 T:41624  NOTICE: PleXBMC -> Authentication error on server [xx.xxx.xx.xxx:13892].  Check user/password.

It occurs after trying to access a section (movies, tv, etc). Username and password are definitely correct.

Hope this helps.

Dan

**Comment by hippojay** [comment]
Thanks.  This is because I have progressively removed the old way of performing authentication, in favour of a new, easier method.  But I've not yet migrated all the different functions to use the new method yet.  So whilst your user/pass is correct, plexbmc isn't actually using these and therefore you are getting the authentication error.  I'll fix these in the next couple of days

**Comment by sintaxasn** [comment]
Aha ;) no worries. Just let me know when fixed and I'll retest. Cheers :)

**Comment by hippojay** [comment]
Ok - all functions migrated to the new authentication method - so hopefully this won't be an issue now.
