### ISSUE TITLE
plexbmc crashes on load  'os.getcwd' to set the path, you cannot do that in a version 2.1.0 plugin

### ISSUE THREAD

**Issue by desean1625** [hippojay/plugin.video.plexbmc#54]
uploaded log snippets to http://xbmclogs.com/pdtupn7b2

Basically I installed the latest commit and it crashed shortly after install. Whole system froze and couldnt even ssh into it.

After the reboot I got the second snippet 'os.getcwd' to set the path, you cannot do that in a version 2.1.0 plugin.

**Comment by hippojay** [comment]
Thanks - not sure why this message is coming up (I don't do any os.getcwd calls).  Looks like it trying to grab the settings for plexbmc, but can't find them on your system - which causes some big problems for kodi.   I certainly wouldn't expect that type of error to kill your system - which is a kodi issue.

What version of kodi is this running and how did you install it.  Was is via a zip file or manually to a folder.  What happens if ou try and open the settings for plexbmc from video -> plugins -> plexbmc (right click/context menu - addon settings)

**Comment by desean1625** [comment]
18:00:09 T:3024601088  NOTICE: Starting Kodi (14.1 Git:Unknown). Platform: Linux ARM 32-bit
18:00:09 T:3024601088  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
18:00:09 T:3024601088  NOTICE: Kodi compiled Jan 30 2015 by GCC 4.9.1 for Linux ARM 32-bit version 3.16.7 (200711)
18:00:09 T:3024601088  NOTICE: Running on Open Source Media Center 0.9.9, kernel: Linux ARM 32-bit version 3.18.5-v7+
18:00:09 T:3024601088  NOTICE: FFmpeg statically linked, version: 77f79f0-xbmc-2.4.6-Helix

**Comment by desean1625** [comment]
Most recent commit this isn't happening anymore.
