### ISSUE TITLE
Kodi pseudolibrary

### ISSUE THREAD

**Issue by Dukobpa3** [hippojay/plugin.video.plexbmc#83]
Hi.
Are you know about this feature?
I think that would be nice to use it instead of skins modifications.
Just sometimes update "pseudolibrary" by timer or callback from PS.
http://kodi.wiki/view/Internet_video_and_audio_streams
http://forum.kodi.tv/showthread.php?tid=205148

**Comment by hippojay** [comment]
I've looked at something similar in the past (i.e. a plex to kodi library sync) - but there are a couple of issues;
* lack of Multiple libraries - everything would have to be merged into a single "movies" or "tv shows"
* No ability to support authentication/myplex/plexhome
* resume syncing might be an issue, or at least be messy.  So "stop and resume" across devices would probably not work correctly.  

However, it might suit some people as a way to integrating directly with a basic KODI install.

**Comment by Dukobpa3** [comment]
Is there any other way for all skins support?
Also would be nice to avoid switch from plex to kodi library and view both in one place.

**Comment by hippojay** [comment]
Agree it would be great if all skins supported this, but the problems is that KODI isn't designed for plex-like libraries/functions and plex isn't designed to delivery KODI-like libraries.  So there is going to be a compromise.

Without authentication, it's slightly easier - perhaps KODI tags or something like that could fake a library - but authentication and the possibility of changing URLs/HTTP Headers means it all gets messy quickly.

What KODI needs is a library replacement addon/service - where queries into the database can be intercepted and different data provided.  Thinking about it, I wonder if a pseudo-database could be created and the incoming SQL caught and data supplied from the plex database.  Performance would probably be terrible, but with some caching might be acceptable.  hmmmm....  Still wouldn't support plexhome though (so maybe a plexhome switcher addon connected to the database)...

**Comment by Dukobpa3** [comment]
Wanna some like this
![kodi library](https://cloud.githubusercontent.com/assets/1858880/7475955/496ab76c-f353-11e4-9c51-72cd912f5801.png)

**Comment by hippojay** [comment]
something like that yes, but I was thinking real-time, rather than periodic sync.  

The plex database is sqlite3 and have a few tables for metadata, parts, libraries.

I had a look to see if there was a federation storage engine for sqlite3, but looks like this doesn't exist (which would have made it easier to use sql as a backend for some views).

So i see a couple of options:
1) frequent sync.  Create a process that frequently (i.e. 5-10 mins) updates the kodi database, both back and forth.    Perhaps adding some custom triggers into a separate "for update" table and using polling this to set of sync activity.  It's going to depend on the time take to sync the data, but parallel queries could do it - sqlite3 and mysql are capable of good transaction speeds.  I would plex this database on the same host as the plex server to make relative media locations easier to handle.

2) mysql proxy.  Create an interface layer that can accept mysql queries, intercept and gather the data from plex.  In essence create a kodi-plex database interface.  Updates and inserts would be the challenge, as well as the translation of events - but I'm guessing that KODI only really has a limited amount of queries that come in.

Perhaps tags - http://kodi.wiki/view/Video_library_tags - could use used to mark data with library names and therefore separate them out.

It's a fair bit of work, but a proof of concept might show if that work was worth it.

**Comment by desean1625** [comment]
Has anyone gotten plexbmc working with pseudo tv? I was just trying to figure it out.
