### ISSUE TITLE
"Viewed" marks is not correct

### ISSUE THREAD

**Issue by Dukobpa3** [hippojay/plugin.video.plexbmc#84]
It was launched from start with continuous playing. Current Episode is №16 and its mark is correct.
But there is much incorrect "partially viewed" marks also.
Same situation with all TV Shows.
![cwahfp8ofug6kzmt9eqnpa 1](https://cloud.githubusercontent.com/assets/1858880/7477467/b46a3eb2-f35c-11e4-9b32-d6305f19b526.jpg)

**Comment by hippojay** [comment]
hmm - when played as a playlist, the player doesn't actually stop playing and therefore the end of the file (i.e. a stop) isn't registered and the file isn't marked as finished.  Need to look at a way of marking this, but might go for a %age complete to mark as watched.

**Comment by hippojay** [comment]
Right - think I have fixed this.  This issue was that play back monitroing wasn;t stopping, as playback wasn;t stopping - so each time a new file played, another monitor was created, tracking the playing time, but reporting it back as the original files playtime.  This is why you had lots of partial plas with the same time - they were all tracking the last items time.  

It was handy having that screenshot, as it gave me some extra info to use.

**Comment by Dukobpa3** [comment]
Nice ))
I'll try tomorrow.
