### ISSUE TITLE
Play all functionality for music

### ISSUE THREAD

**Issue by MaximilianBuegler** [hippojay/plugin.video.plexbmc#92]
Hallo,

It would be great if I could go onto a music folder, like an artist or an album and have a "play all" option in the context menu, like I have in plex/web. Also if I click on a single track in an album, only that one track is played. It would be awesome if it would just continue playing the following tracks like it does when playing local music in kodi. Currently, to play an album I have to go to the first track and in the context menu select 'play from here'. In kodi usually that would be the default action. Or am I missing something here?

Thanks a lot

homernl82

**Comment by hippojay** [comment]
when playing music, kodi shuold play through the onscreen tracks automatically - assume that yuo have the option select in the kodi settings (under Audio I think).  I'll have a look

**Comment by homernl82** [comment]
I'm quite sure it doesn't. The option is enabled, as for local music it works just fine. I'll check as soon as I can. Besides that enabling the P key when an album is selected, in order to play the entire album or have a "Play" entry in the context menu, would be great. There's no need to browse into the album when I just want to play it entirely.
