### ISSUE TITLE
OSMC skin support

### ISSUE THREAD

**Issue by iBobik** [hippojay/plugin.video.plexbmc#95]
Could you add support for OSMC skin or other skins what look more attractive and perform better than Amber? (I am using Raspberry Pi and performance of most skins compared to OSMC is very big difference.)

**Comment by Dukobpa3** [comment]
Which kind of skin support are you want?
You can use this addon in any skin through 
```
addons->audio/video/pictures->PleXBMC
```

**Comment by hippojay** [comment]
@iBobik Adding skin support is a time intensive task and unfortunately can vary from skin to skin.  Originally I started out providing skins - but the overhead was too great.

The best bet would be to approach the skin owners and see if they would be willing to accept any plexbmc specific skin additions.  It's slightly easier to push code into a skin that it being maintained.

As an alternative, @randomevents was looking to see if we can use "dynamic listitems" instead of skin variable to provide plexbmc integration into skins.  This would make it easier to insert home items into skins ( a few lines, rather than a few hundred).  However this work has not yet been completed (or even started - not sure what the state is).

**Comment by iBobik** [comment]
Hi,
I hope trend is to allow user customize main menu and it's submenu and widget, so user can choose to open plexbmc listing on some menu item.

But very good UX pattern in Kodi is to show some "deck" on menu item focus. This works well with Kodi's internal library, but not works with external libraries provided by addons like plexbmc.

Jan Pobořil
http://honza.poboril.cz/

11 May 2015 v 11:51, hippojay <notifications@github.com>:

**Comment by randomevents** [comment]
as @hippojay stated, I am working on the dynamic skin, I had to get up to speed on the XBMC skinning first, hopefully I'll have something to show soon (I need it for my own system!).

**Comment by iBobik** [comment]
Nice :-)

Jan Pobořil
http://honza.poboril.cz/

16 May 2015 v 14:41, randomevents <notifications@github.com>:

**Comment by Cessquill** [comment]
@Dukobpa3 I think what the original poster is asking for is if it's possible for the OSMC skin to be modified.

This skin comes with OSMC (which used to be Raspbmc) and is suited for the Raspberry Pi and a dedicated media box that I think the software author is selling now.

It's a very lightweight and clean script that makes the Pi zip along.

I'm personally using it, since it's the only way to get live TV decently over my network.  If I can get seamless Plex integration in there too I can go back to having one media player.

However, going down the alternate route that that @randomevents is taking looks promising. Look forward to it.

**Comment by desean1625** [comment]
You can put a feature request in on the osmc repo. 
https://github.com/osmc/osmc
